workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' # Merge request event
    - if: $CI_COMMIT_TAG # Tags
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Default branch
    - if: '$CI_PIPELINE_SOURCE == "schedule"' # Scheduled pipeline
    - if: '$CI_PIPELINE_SOURCE == "web"' # Web UI

default:
  image: rust:bullseye
  before_script:
    - rustc --version
    - cargo --version
  tags:
    - shared-fi

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - cargo build --verbose

fmt:
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  allow_failure: true

clippy:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  allow_failure: true

test:
  stage: test
  script:
    - cargo test --verbose
